services:
  frontend:
    build: ./bank-web-app-frontend
    container_name: frontend_c
    ports:
      - '3000:3000'

  postgres:
    image: postgres:14.1-alpine
    container_name: mypostgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local