\c postgres

-- Insert admin user (replace password_hash with actual hash generated by your application)
INSERT INTO users (
    email,
    password_hash,
    role,
    status,
    email_verified_at
) VALUES (
    'admin@example.com',
    'kjadsfjahsdlgaslkdj&&lkjad',
    'admin',
    'active',
    CURRENT_TIMESTAMP
);